layout_spectrum: 0.18003542511723936
typography_spectrum: 0.024143290240317583
color:
  brandStrength: 0.5791984845418483
  lightness: 0.8619726600591093
  saturation: 0.4603116945363581
  rhythmicContrast: 0.38539761188440025
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
content_rating:
  adult: false
author:
  name: Pankaj Sharma
  email: pankajsharma.blue@hotmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/cee2130b-d9c4-4d5b-aaff-31b6f0d32edb.gif
name: bikeholiday.photo
navigation:
  - name: 'Paris Lourdes Cycle Trip '
    id: 7ec0a487-79f1-4892-91e2-33bdad93c7a7
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/13401e8c-f943-45fd-ab19-d18905a788b2.ico
title: Welcome on My Cycle Trips
description: Put some fun between your legs
content: []
github: true
analytics:
  google: pankaj.purple@gmail.com
