typography_spectrum: 0.024143290240317583
content_rating:
  adult: false
color:
  brandStrength: 0.5791984845418483
  lightness: 0.8619726600591093
  saturation: 0.4603116945363581
  rhythmicContrast: 0.38539761188440025
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
github: true
layout_spectrum: 0.18003542511723936
analytics:
  google: '92958184'
author:
  name: Pankaj Sharma
  email: pankajsharma.blue@hotmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/cee2130b-d9c4-4d5b-aaff-31b6f0d32edb.gif
name: bikeholiday.photo
navigation:
  - name: About us
    id: cb0a18d3-9204-422c-b971-8dcc000d17ad
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/13401e8c-f943-45fd-ab19-d18905a788b2.ico
title: Camino del Norte
content:
  - id: !<tag:yaml.org,2002:js/undefined> ''
    type: image
    html: >-
      <img
      src="https://the-grid-user-content.s3-us-west-2.amazonaws.com/ec803a1f-7d6b-479c-868f-f34c13ab87f2.jpg">
    src: >-
      https://the-grid-user-content.s3-us-west-2.amazonaws.com/ec803a1f-7d6b-479c-868f-f34c13ab87f2.jpg
    metadata:
      datePublished: null
      keywords: []
      related: []
      author: []
      '@context': 'http://schema.org'
      '@type': MediaObject
      app_links: []
      publisher:
        url: 'https://the-grid-user-content.s3-us-west-2.amazonaws.com'
        name: The-grid-user-content
        favicon: null
        domain: the-grid-user-content.s3-us-west-2.amazonaws.com
      description: ''
    title: !<tag:yaml.org,2002:js/undefined> ''
    caption: !<tag:yaml.org,2002:js/undefined> ''
    text: !<tag:yaml.org,2002:js/undefined> ''
description: Step by Step to Santiago
purpose:
  - type: contact
    url: 'mailto:pankajsharma.blue@hotmail.com'
    label: Contact me
