typography_spectrum: 0.866176875308156
content_rating:
  adult: false
color:
  brandStrength: 0.08896255004219711
  lightness: 0.16439570486545563
  saturation: 0.8487856569699943
  rhythmicContrast: 0.6459825546480715
  brandColors:
    - '#71A7FE'
    - '#399AE7'
    - '#3B407C'
    - '#547AB1'
    - '#CEAFC0'
layout_spectrum: 0.4765815772116184
author:
  name: Pankaj Sharma
  email: pankajsharma.blue@hotmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/cee2130b-d9c4-4d5b-aaff-31b6f0d32edb.gif
name: lifeonpedals.bike
navigation:
  - name: 'Paris Lourdes Cycle Trip '
    id: 7ec0a487-79f1-4892-91e2-33bdad93c7a7
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/13401e8c-f943-45fd-ab19-d18905a788b2.ico
title: Welcome to My Cycle Trips
description: Put something fun between your legs
