typography_spectrum: 0.736997575731948
content_rating:
  adult: false
color:
  brandStrength: 0.837539607193321
  lightness: 0.7679354203864932
  saturation: 0.9916833690367639
  rhythmicContrast: 0.9979483517818153
  brandColors:
    - '#FFFFFF'
    - '#CCCCCC'
    - '#999999'
    - '#4D4D4D'
    - '#333333'
layout_spectrum: 0.041639643954113126
author:
  name: Pankaj Sharma
  email: pankajsharma.blue@hotmail.com
logo: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/cee2130b-d9c4-4d5b-aaff-31b6f0d32edb.gif
name: lifeonpedals.bike
navigation:
  - name: 'Paris Lourdes Cycle Trip '
    id: 7ec0a487-79f1-4892-91e2-33bdad93c7a7
    type: content
favicon: >-
  https://the-grid-user-content.s3-us-west-2.amazonaws.com/13401e8c-f943-45fd-ab19-d18905a788b2.ico
title: Welcome on My Cycle Trips
description: Put some fun between your legs
